standard = "1993"

[libraries]
components.files = ['components/*.vhd', 'src/*.vhd', 'src/*/*.vhd']

[lint]
unused = 'warning'              # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = true # Disable linting for the 'library work;' statement
